# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"http://www.{default}/":
    type: upstream
    upstream: "drupal:http"

"http://{default}/":
    type: upstream
    upstream: "drupal:http"

